###### Thingspeak API ######

# feeds
DEFAULT_THINGSPEAK_FEEDS_INTERVAL_DAYS = 7
THINGSPEAK_FEEDS_LIST_MAX_NUM_RESULTS = 8000
THINGSPEAK_FEEDS_LIST_URL = 'http://thingspeak.com/channels/{}'

# channels
MATHWORKS_USER_ID = 'baurd'
THINGSPEAK_CHANNELS_LIST_URL = 'https://api.thingspeak.com/channels.json'
AIR_QUALITY_MONITOR_KEYWORD = 'AIRQO'
INACTIVE_MONITOR_KEYWORD = 'INACTIVE'
API_KEY_CONFIG_VAR_NAME = 'CHANNEL_{}_API_KEY'
AIRQO_CHANNEL_TYPE = 'airqo'
SOIL_CHANNEL_TYPE = 'soil'
LAST_CHANNEL_UPDATE_TIME_GLOBARLVAR_NAME = 'LAST_CHANNEL_UPDATE_TIME'

# Incidents
NO_DATA_MALFUNCTION_REASON_STR = 'no_data'
LOW_BATTERY_MALFUNCTION_REASON_STR = 'low_battery_voltage'
LOW_REPORTING_FREQUENCY_MALFUNCTION_REASON_STR = 'low_reporting_frequency'
REPORTING_OUTLIERS_MALFUNCTION_REASON_STR = 'reporting_outliers'

# Misc constants
PYTZ_KAMPALA_STRING = 'Africa/Kampala'
