# Generated by Django 2.1.2 on 2018-10-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airqo_monitor', '0002_auto_20181023_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('channel_id', models.IntegerField()),
                ('note', models.TextField()),
                ('author', models.TextField()),
            ],
            options={
                'db_table': 'channel_note',
            },
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
