# Generated by Django 2.1.2 on 2018-10-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airqo_monitor', '0002_auto_20181023_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('channel_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.TextField(null=True)),
            ],
            options={
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='ChannelNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('note', models.TextField()),
                ('author', models.TextField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airqo_monitor.Channel')),
            ],
            options={
                'db_table': 'channel_note',
            },
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='channel_id',
        ),
        migrations.AddField(
            model_name='incident',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='airqo_monitor.Channel'),
            preserve_default=False,
        ),
    ]
