# Generated by Django 2.1.2 on 2018-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airqo_monitor', '0003_auto_20181024_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
