# Generated by Django 2.1.2 on 2018-10-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airqo_monitor', '0004_incident_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='channel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='airqo_monitor.Channel'),
            preserve_default=False,
        ),
    ]
