# Generated by Django 2.1.2 on 2018-10-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airqo_monitor', '0004_incident_resolved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='channel',
        ),
    ]
