# Generated by Django 2.1.2 on 2018-11-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airqo_monitor', '0006_auto_20181101_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='reason',
            new_name='malfunction_reason',
        ),
    ]
