# Generated by Django 2.1.2 on 2018-11-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airqo_monitor', '0006_auto_20181031_1026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incidentmalfunctionreasonlink',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='incidentmalfunctionreasonlink',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='incidentmalfunctionreasonlink',
            name='malfunction_reason',
        ),
        migrations.AddField(
            model_name='incident',
            name='malfunction_reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='airqo_monitor.MalfunctionReason'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IncidentMalfunctionReasonLink',
        ),
    ]
