# Generated by Django 2.1.2 on 2018-11-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airqo_monitor', '0008_channel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('name', models.TextField(db_index=True)),
                ('friendly_name', models.TextField()),
                ('data_format_json', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'channel_type',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='airqo_monitor.ChannelType'),
        ),
    ]
