# Generated by Django 2.1.2 on 2018-11-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airqo_monitor', '0009_auto_20181105_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='airqo_monitor.ChannelType'),
            preserve_default=False,
        ),
    ]
